language: zh
enable_event_embedding: true
profile_strict_mode: true

event_tags:
  - name: "心理健康"
    description: |
      您需要观察用户的心理健康状态，从以下列表中选择最相关的标签：
      - 焦虑
      - 愤怒
      - 悲伤
      - 快乐
    
overwrite_user_profiles:
  - topic: "基本信息"
    sub_topics:
      - name: "姓名"
      - name: "年龄"
      - name: "性别"
      - name: "职业"
      - name: "地点"
      - name: "时区"
        description: "用户的本地时区，用于时间安排"

  - topic: "AI伴侣偏好"
    sub_topics:
      - name: "交互风格"
        description: "正式、随意、友好、专业等"
      - name: "感兴趣话题"
        description: "偏好的对话主题"
      - name: "学习目标"
        description: "想要学习或实现的目标"